//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPM_HTQLNH_SHARE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Nullable<int> id { get; set; }
        public string res_id { get; set; }
        public int login_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<long> avartar { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<int> user_create { get; set; }
        public Nullable<int> status { get; set; }
        public string description { get; set; }
        public string touch_id { get; set; }
        public string address { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
