//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPM_HTQLNH_SHARE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<decimal> totalAmountWithVat { get; set; }
        public Nullable<decimal> discountAmount { get; set; }
        public string description { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> invoice_id { get; set; }
        public Nullable<bool> promotion { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> quantity { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
