//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPM_HTQLNH_SHARE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogsApi
    {
        public Nullable<System.DateTime> request_date { get; set; }
        public string request_content { get; set; }
        public string request_response { get; set; }
        public string endpoint { get; set; }
        public string type { get; set; }
        public string client_session { get; set; }
        public int id { get; set; }
    }
}
