//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPM_HTQLNH_SHARE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuGroup
    {
        public int id { get; set; }
        public string res_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<int> user_create { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
