//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPM_HTQLNH_SHARE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table()
        {
            this.TableOrders = new HashSet<TableOrder>();
        }
    
        public int id { get; set; }
        public string res_id { get; set; }
        public string model { get; set; }
        public string name { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<int> user_create { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<decimal> p2d_x { get; set; }
        public Nullable<decimal> p2d_y { get; set; }
        public Nullable<int> order_status { get; set; }
        public Nullable<int> parent { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableOrder> TableOrders { get; set; }
        public virtual User User { get; set; }
    }
}
