//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPM_HTQLNH_SHARE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableOrder
    {
        public int id { get; set; }
        public Nullable<int> dishid { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<int> table_id { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Table Table { get; set; }
    }
}
