//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPM_HTQLNH_SHARE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Restaurant
    {
        public int user_id { get; set; }
        public string res_id { get; set; }
        public Nullable<int> type { get; set; }
        public string note { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
